
### Получить всю историю, всех  пользователей
Get  http://localhost:8080/history


### Получить всю историю, одного  пользователея
Get  http://localhost:8080/historyUser/53aa35c8-e659-44b2-882f-f6a56e443c90


### Создать историю для пользователя.
POST http://localhost:8080/history
Content-type: application/json; charset=utf-8

{
    "UserUuid": "53aa35c8-e659-44b2-882f-f6a56e443c90",
    "Query": "John Coltrane11"
}

### Обновить у истории Ответ и Классификацию(ID)
PUT http://localhost:8080/history/ResponceAndClassificationId
Content-type: application/json; charset=utf-8

{
    "ID": 119272,
    "Responce": "{\"name\": \"Responce2\"}",
    "ClassificationId": null

}



### Обновить у истории Ответ и Классификацию(Name)
PUT http://localhost:8080/history/ResponceAndClassificationName
Content-type: application/json; charset=utf-8

{
    "ID": 119272,
    "Responce": "{\"name\": \"Responce12\"}",
    "ClassificationName": "erger"

}


### Обновить рейтинг у истории
PUT http://localhost:8080/history/Rating
Content-type: application/json; charset=utf-8

{
    "ID": 2,
    "Rating": 10
}

### Получить все классификации
Get  http://localhost:8080/classification

### Добавить классификацию
POST http://localhost:8080/classification
Content-type: application/json; charset=utf-8

{
    "Name": "Сергей22"
}