
Get  http://localhost:8080/history


###
Get  http://localhost:8080/historyUser/53aa35c8-e659-44b2-882f-f6056e443c90


###
POST http://localhost:8080/history
Content-type: application/json; charset=utf-8

{
    "UserUuid": "53aa35c8-e659-44b2-882f-f6056e443c90",
    "Query": "John Coltrane11"
}

###
PUT http://localhost:8080/history/ResponceAndClassificationId
Content-type: application/json; charset=utf-8

{
    "ID": 2,
    "Responce": "Responce2",
    "ClassificationId": null

}

###
PUT http://localhost:8080/history/Rating
Content-type: application/json; charset=utf-8

{
    "ID": 2,
    "Rating": 10
}

###

Get  http://localhost:8080/classification

###
POST http://localhost:8080/classification
Content-type: application/json; charset=utf-8

{
    "Name": "Сергей22"
}